"""empty message

Revision ID: b7df2c111660
Revises: 33fcaff39e3b
Create Date: 2025-06-21 14:44:06.477839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7df2c111660'
down_revision = '33fcaff39e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='user.id'),
    sa.Column('follower_id', sa.Integer(), nullable=False, foreign_key='user.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
